version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/app.genemco.com/

permissions:
  - object: /var/www/app.genemco.com
    pattern: "**"
    owner: root
    mode: 777
    type:
      - directory

permissions:
  - object: /var/www
    pattern: "**"
    owner: root
    mode: 777
    type:
      - directory

#permissions:
#  - object: /var/www/app.genemco.com/storage/logs
#    pattern: "**"
#    owner: root
#    mode: 777
#    type:
#      - file
