version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app.genemco.com/

permissions:
  - object: /var/www/app.genemco.com/
    pattern: "**"
    owner: root
    mode: 775
    type:
      - directory

permissions:
  - object: /var/www/app.genemco.com/storage/
    pattern: "logs"
    owner: root
    mode: 777
    type:
      - directory

permissions:
  - object: /var/www/app.genemco.com/storage/logs/
    pattern: "*.log"
    owner: root
    mode: 777
    type:
      - file

permissions:
  - object: /var/www/app.genemco.com/bootstrap/
    pattern: "**"
    owner: root
    mode: 777
    type:
      - directory
